#!/bin/bash

VERSION=$1
CHANGELOG_FILE="../CHANGELOG.md"
START=$(grep -n "## \[${VERSION}\]" "${CHANGELOG_FILE}" | cut -d : -f 1)
END_VERSION=$(grep "## \[" ../CHANGELOG.md | cut -d"[" -f2 | cut -d"]" -f1 | grep -v 1.1.0 | head -1)
END=$(grep -n "## \[${END_VERSION}\]" ${CHANGELOG_FILE} | cut -d : -f 1)
cat "${CHANGELOG_FILE}" | tail -n +"$((START + 3))" | head -n "$((END - START - 4))"
